"""Provider-independent capability protocols and data contracts."""

from agentrig.capabilities.base import (
    CapabilityDescriptor,
    CapabilityFeature,
    CapabilityKind,
    CapabilityLimit,
    CapabilityRequirements,
    DataRetention,
)
from agentrig.capabilities.coding import (
    ChangedFileEvidence,
    CodingAgent,
    CodingChangeKind,
    CodingResult,
    CodingStatus,
    CodingTask,
    CodingValidationStatus,
    ValidationEvidence,
    WorkspaceAuthorization,
)
from agentrig.capabilities.image_generation import (
    ImageGenerationRequest,
    ImageGenerationResult,
    ImageGenerator,
    ImageRegion,
    ImageSize,
    ImageSpecification,
)
from agentrig.capabilities.retrieval import (
    RetrievalFilter,
    RetrievalMatch,
    RetrievalRequest,
    RetrievalResult,
    RetrievalScore,
    RetrievedChunk,
    RetrievedDocument,
    Retriever,
)
from agentrig.capabilities.search import (
    SearchCitation,
    SearchHit,
    SearchProvider,
    SearchRequest,
    SearchResult,
    SearchRetrievalMetadata,
)
from agentrig.capabilities.text_generation import (
    GenerationUsage,
    ModelMetadata,
    TextGenerationFinishReason,
    TextGenerationRequest,
    TextGenerationResult,
    TextGenerator,
    TextMessage,
    TextMessageRole,
)
from agentrig.capabilities.structured_generation import (
    StructuredGenerationRequest,
    StructuredGenerationResult,
    StructuredGenerator,
    StructuredOutputSchema,
)

__all__ = (
    "CapabilityDescriptor",
    "CapabilityFeature",
    "CapabilityKind",
    "CapabilityLimit",
    "CapabilityRequirements",
    "ChangedFileEvidence",
    "CodingAgent",
    "CodingChangeKind",
    "CodingResult",
    "CodingStatus",
    "CodingTask",
    "CodingValidationStatus",
    "DataRetention",
    "GenerationUsage",
    "ImageGenerationRequest",
    "ImageGenerationResult",
    "ImageGenerator",
    "ImageRegion",
    "ImageSize",
    "ImageSpecification",
    "ModelMetadata",
    "RetrievalFilter",
    "RetrievalMatch",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievalScore",
    "RetrievedChunk",
    "RetrievedDocument",
    "Retriever",
    "SearchCitation",
    "SearchHit",
    "SearchProvider",
    "SearchRequest",
    "SearchResult",
    "SearchRetrievalMetadata",
    "StructuredGenerationRequest",
    "StructuredGenerationResult",
    "StructuredGenerator",
    "StructuredOutputSchema",
    "TextGenerationFinishReason",
    "TextGenerationRequest",
    "TextGenerationResult",
    "TextGenerator",
    "TextMessage",
    "TextMessageRole",
    "ValidationEvidence",
    "WorkspaceAuthorization",
)
