python_library(
    name = "ollama",
    srcs = [
        "__init__.py",
        "ollama.py",
        "runtime.py",
    ],
    base_module = "agentrig.integrations.ollama",
    deps = [
        "//src/agentrig/agents:agents",
        "//src/agentrig/capabilities:capabilities",
        "//src/agentrig/core:core",
    ],
    visibility = ["PUBLIC"],
)

python_library(
    name = "ollama_sdk",
    srcs = ["sdk.py"],
    base_module = "agentrig.integrations.ollama",
    deps = [
        ":ollama",
        "//src/agentrig/core:core",
        "//third_party/python:extra-ollama",
    ],
    visibility = ["PUBLIC"],
)
