python_library(
    name = "workflow",
    srcs = glob(["*.py"]),
    base_module = "agentrig.workflow",
    deps = [
        "//src/agentrig/agents:agents",
        "//src/agentrig/core:core",
    ],
    visibility = ["PUBLIC"],
)
