python_library(
    name = "package",
    srcs = [
        "__init__.py",
        "fundamentals/__init__.py",
        "workflows/__init__.py",
    ],
    base_module = "examples",
    visibility = ["PUBLIC"],
)
