python_library(
    name = "testing",
    srcs = glob(["*.py"]),
    base_module = "agentrig.testing",
    deps = [
        "//src/agentrig/agents:agents",
        "//src/agentrig/core:core",
    ],
    visibility = ["PUBLIC"],
)
