python_library(
    name = "agentrig",
    srcs = glob(["agentrig/**/*.py"]),
    base_module = "",
    resources = ["agentrig/py.typed"],
    deps = [
        "//src/agentrig/agents:agents",
        "//src/agentrig/core:core",
        "//src/agentrig/evals:evals",
        "//src/agentrig/testing:testing",
        "//src/agentrig/workflow:workflow",
    ],
    tests = ["//tests/unit:unit"],
    visibility = ["PUBLIC"],
)
